# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaeditarprodutocadastrado.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditarProdutos(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 313)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 531, 321))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 209, 101);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(340, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.editarinputname = QtWidgets.QLineEdit(Dialog)
        self.editarinputname.setGeometry(QtCore.QRect(230, 150, 111, 41))
        self.editarinputname.setObjectName("editarinputname")
        self.editarinputnpreco = QtWidgets.QLineEdit(Dialog)
        self.editarinputnpreco.setGeometry(QtCore.QRect(340, 150, 91, 41))
        self.editarinputnpreco.setObjectName("editarinputnpreco")
        self.btnsalvar = QtWidgets.QPushButton(Dialog)
        self.btnsalvar.setGeometry(QtCore.QRect(180, 200, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnsalvar.setFont(font)
        self.btnsalvar.setStyleSheet("color: rgb(0, 0, 182);\n"
"background-color: rgb(255, 255, 255);")
        self.btnsalvar.setObjectName("btnsalvar")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 521, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 120, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(150, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.editarinputcodig = QtWidgets.QLineEdit(Dialog)
        self.editarinputcodig.setGeometry(QtCore.QRect(150, 150, 81, 41))
        self.editarinputcodig.setObjectName("editarinputcodig")
        self.editarinputid = QtWidgets.QLineEdit(Dialog)
        self.editarinputid.setGeometry(QtCore.QRect(70, 150, 81, 41))
        self.editarinputid.setObjectName("editarinputid")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TELA PARA EDITAR PRODUTOS"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">NOME</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">PREÇO</p></body></html>"))
        self.editarinputname.setPlaceholderText(_translate("Dialog", "Editar nome da carne"))
        self.editarinputnpreco.setPlaceholderText(_translate("Dialog", "Editar preço"))
        self.btnsalvar.setText(_translate("Dialog", "SALVAR"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">EDITAR PRODUTOS</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">ID</p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">CÓDIGO</p></body></html>"))
        self.editarinputcodig.setPlaceholderText(_translate("Dialog", "Editar Código"))
        self.editarinputid.setPlaceholderText(_translate("Dialog", "Editar ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_EditarProdutos()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
