# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telalogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(764, 558)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-10, 0, 781, 561))
        self.label.setMinimumSize(QtCore.QSize(211, 0))
        self.label.setStyleSheet("background-color: rgb(0, 209, 101);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 170, 191, 81))
        self.label_2.setStyleSheet("image: url(:/img/user.png);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 170, 211, 81))
        self.label_3.setStyleSheet("image: url(:/img/icons/user.png);")
        self.label_3.setObjectName("label_3")
        self.btnentrar = QtWidgets.QPushButton(Dialog)
        self.btnentrar.setGeometry(QtCore.QRect(300, 370, 161, 51))
        self.btnentrar.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 22pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.btnentrar.setObjectName("btnentrar")
        self.namedouser = QtWidgets.QLineEdit(Dialog)
        self.namedouser.setGeometry(QtCore.QRect(270, 200, 201, 41))
        self.namedouser.setText("")
        self.namedouser.setObjectName("namedouser")
        self.passwduser = QtWidgets.QLineEdit(Dialog)
        self.passwduser.setGeometry(QtCore.QRect(270, 290, 201, 41))
        self.passwduser.setText("")
        self.passwduser.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwduser.setObjectName("passwduser")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 500, 231, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(200, 80, 341, 71))
        self.label_5.setStyleSheet("color: rgb(227, 227, 227);\n"
"font: 75 16pt \"Segoe UI\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(90, 10, 591, 81))
        self.label_6.setStyleSheet("color: rgb(227, 227, 227);\n"
"font: 75 16pt \"Segoe UI\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(80, 260, 211, 81))
        self.label_7.setStyleSheet("image: url(:/img/icons/pass.png);")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tela Login"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#ffaa00;\"><br/></span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btnentrar.setText(_translate("Dialog", "Entrar"))
        self.namedouser.setPlaceholderText(_translate("Dialog", "Digite nome do usuário:"))
        self.passwduser.setPlaceholderText(_translate("Dialog", "Digite sua senha:"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">Esqueceu sua senha?</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">Login usuário:</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;\">MERCADO</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
import template.img


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
