# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telacadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastrar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(719, 467)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 751, 481))
        self.label.setStyleSheet("font: 75 italic 26pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 209, 101);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 91, 31))
        self.label_2.setStyleSheet("font: 75 italic 20pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 91, 31))
        self.label_3.setStyleSheet("font: 75 italic 20pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 111, 31))
        self.label_4.setStyleSheet("font: 75 italic 20pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.inputname = QtWidgets.QLineEdit(Dialog)
        self.inputname.setGeometry(QtCore.QRect(130, 140, 181, 31))
        self.inputname.setObjectName("inputname")
        self.inputtel = QtWidgets.QLineEdit(Dialog)
        self.inputtel.setGeometry(QtCore.QRect(130, 189, 181, 31))
        self.inputtel.setObjectName("inputtel")
        self.inputend = QtWidgets.QLineEdit(Dialog)
        self.inputend.setGeometry(QtCore.QRect(130, 239, 181, 31))
        self.inputend.setObjectName("inputend")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(380, 100, 261, 191))
        self.label_5.setStyleSheet("image: url(:/add/icons/cadastrar-img.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(140, 30, 411, 81))
        self.label_6.setStyleSheet("font: 75 28pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.btnadd = QtWidgets.QPushButton(Dialog)
        self.btnadd.setGeometry(QtCore.QRect(70, 330, 151, 41))
        self.btnadd.setStyleSheet("font: 75 20pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.btnadd.setObjectName("btnadd")
        self.btncancel = QtWidgets.QPushButton(Dialog)
        self.btncancel.setGeometry(QtCore.QRect(230, 330, 151, 41))
        self.btncancel.setStyleSheet("font: 75 20pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.btncancel.setObjectName("btncancel")
        self.btnlimp = QtWidgets.QPushButton(Dialog)
        self.btnlimp.setGeometry(QtCore.QRect(390, 330, 151, 41))
        self.btnlimp.setStyleSheet("font: 75 20pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.btnlimp.setObjectName("btnlimp")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tela de Cadastro"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Nome:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Telefone:</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Endereço:</span></p></body></html>"))
        self.inputname.setPlaceholderText(_translate("Dialog", "Insira seu nome"))
        self.inputtel.setPlaceholderText(_translate("Dialog", "Insira seu telefone"))
        self.inputend.setPlaceholderText(_translate("Dialog", "Insira seu endereço"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">CADASTRAR CLÍENTES</span></p></body></html>"))
        self.btnadd.setText(_translate("Dialog", "CADASTRAR"))
        self.btncancel.setText(_translate("Dialog", "CANCELAR"))
        self.btnlimp.setText(_translate("Dialog", "LIMPAR"))
import template.cadastro


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Cadastrar()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
